AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  SuggestExtensions: false
Style/Documentation:
  Exclude:
    - "spec/**/*"
    - "benchmarks/**/*"
    - "lib/openapi_first/json_refs.rb"
Style/ExponentialNotation:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "*.gemspec"
Metrics/MethodLength:
  Max: 20
